apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-a-frontend
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Project-A-Kubernetes/Project__A_Helm_Chart_Frontend-.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
    syncOptions:
      - CreateNamespace=true