apiVersion: v1
kind: Service
metadata:
  name: {{ include "project_A_helm_frontend.fullname" . }}
  labels:
    app: {{ .Values.service.label}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    
    - port: {{ .Values.service.matricsPort }}
      targetPort: nginx-metrics
      protocol: TCP
      name: {{ .Values.service.matricsName }}
  selector:
    {{- include "project_A_helm_frontend.selectorLabels" . | nindent 4 }}
